# site properties and page defaults
title: MetaIoT @ HUST
subtitle: Welcome to MetaIoT Lab.
description: We create the next generation of intelligent wireless systems for communication and sensing with applications in autonomous systems, mixed reality, and IoT.
header: images/background.webp
footer: images/background.webp
proofer: false

# site social media and other links
links:
  email: weiwangw@hust.edu.cn
  google-scholar: YkD8hs0AAAAJ
  github: weisgroup

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles
  style: compressed

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
